apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: grpc
    port: {{ .Values.grpcPort }}
    protocol: TCP
    targetPort: {{ .Values.grpcPort }}
  - name: http
    port: {{ .Values.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.httpPort }}
  - name: metrics
    port: {{ .Values.prometheus.metricsPort }}
    targetPort: {{ .Values.prometheus.metricsPort }}
  selector:
    app: {{ .Release.Name }}
